site_name: No Clocks Operations
site_description: Operations documentation for No Clocks, LLC.
site_author: No Clocks, LLC
site_url: https://docs.noclocks.dev/operations

docs_dir: docs
site_dir: site

repo_url: https://github.com/noclocks/operations
repo_name: noclocks/operations
edit_uri: edit/main/docs/

plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: noclocks/cdn
  #     branch: main
  # - git-authors

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noclocks
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noclocksdev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/noclocks
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/noclocks
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/noclocksdev
    - icon: fontawesome/brands/slack
      link: https://noclocks.slack.com
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/noclocksdev
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/noclocks

copyright: Copyright &copy; 2024 No Clocks, LLC

theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode

nav:
  - Home: index.md
  - about.md
  - Contact: contact.md
  - License: license.md
  - Business:
    - 'Business Plan': business/business-plan.md
    - Principles: business/principles.md
    - Startup:
      - 'Startup Checklist': startup/startup-checklist.md
      - 'Startup One-Pager': startup/startup-one-pager.md
      - 'Startup Notes': startup/startup-notes.md
  - Design:
    - design/index.md
    - Brand:
      - design/brand.md
      - 'Brand Kit': design/brand-kit.md
      - 'Brand Book': design/brandbook.md
    - Colors: brand/colors.md
    - Logo: 
      - design/logo.md
      - 'Logo Configuration': design/logo-config.md
    - 'Brand Assets': design/static-assets.md
    - Typography: design/typography.md
    - 'Web Design': design/webdesign.md
  - Finance:
    - finance/index.md
    - 'Financial Strategy': finance/financial-strategy-guide.md
    - 'Pricing': finance/pricing.md
    - 'Financial Systems': finance/systems.md
    - 'Tax Deductions': finance/tax-deductions.md
    - Funding: finance/funding.md
    - 'Startup Costs': finance/startup-costs.md
    - 'Expense Categories': finance/business-expense-categories.md
    - 'Marketing Expenses': finance/marketing-expenses.md
    - 'Sales': finance/sales.md
    - QuickBooks: finance/quickbooks.md
    - Relay: finance/relay.md
  - Marketing:
    - CRM: marketing/crm.md
    - 'Email Marketing': marketing/email-services.md
    - 'Google Adwards': marketing/google-ads.md
    - 'Social Media': marketing/social.md
  - Legal:
    - legal/index.md
  - Development:
    - Languages: dev/languages.md
    - Frameworks: dev/frameworks.md
    - 'Operating Systems': dev/os.md
    - Documentation: dev/documentation.md
    - Databases: dev/databases.md
    - Containers: dev/containers.md
    - 'Version Control': dev/vc.md
    - DevOps: dev/devops.md
    - Cloud: dev/cloud.md
    - 'Infrastructure as Code': dev/iac.md
    - APIs: dev/apis.md
    - 'Developer Experience (DevX)': dev/devx.md
    - 'User Experience (UX)': dev/ux.md
  - Operations:
    - ops/index.md
    - ops/analytics.md
    - ops/roles-and-responsibilities.md
    - ops/skills-inventory.md

